baseURL = 'https://rollaattorimarssi.fi/'
languageCode = 'fi-FI'
title = 'Rollaattorimarssi'

[menus]
  [[menus.main]]
    name = 'Etusivu'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Meistä'
    pageRef = '/meista'
    weight = 20

  [[menus.main]]
    name = 'Marssi ja Ohjelma'
    pageRef = '/marssi-ja-ohjelma'
    weight = 30

  [[menus.main]]
    name = 'Kumppaniksi'
    pageRef = '/kumppaniksi'
    weight = 40

  [[menus.main]]
    name = 'Järjestä paikkakunnallasi'
    pageRef = '/jarjesta-omalla-paikkakunnallasi'
    weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
